update jersy-servlet version from 1.13 to 1.19, aviod jar hell which cause 'java.lang.NoSuchMethodError: javax.ws.rs.core.Application.getProperties()Ljava/util/Map' exception when zeppelin start